version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    container_name: docker-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring_network
    restart: always

  grafana:
    image: grafana/grafana
    container_name: docker-grafana
    user: root
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - monitoring_network

  loki:
    image: grafana/loki:master
    container_name: docker-loki
    ports:
      - "3100:3100"
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    depends_on:
      - grafana
    networks:
      - monitoring_network

networks:
  monitoring_network:
    name: server_network
    driver: bridge
    external: true