global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "dev-pawith"
    static_configs:
    - targets: ['dev.pawith.com:8079']
    metrics_path: /actuator/prometheus
    scrape_interval: 1s

  - job_name: "prod-pawith"
    static_configs:
    - targets: ['api.pawith.com:8079']
    metrics_path: /actuator/prometheus
    scrape_interval: 1s
