version: '3.8'

services:
  mongoDB:
    image: mongo
    container_name: docker-mongoDB
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - server_network

  loganalyzer:
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}
    container_name: ${DOCKER_REPOSITORY}
    restart: always
    ports:
      - "8080:8080"
      - "8079:8079"
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - mongoDB
    networks:
      - server_network

networks:
  server_network:
    driver: bridge
    external: true