version: '3.8'

services:
  mongoDB:
    image: mongo:latest
    container_name: docker-mongoDB
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  logAnalyzer:
    image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}
    container_name: docker-LogAnalyzer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongoDB