name: CD

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: monitoring-docker-compose push
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          source: "./monitoring"
          target: "/home/ubuntu"